### ISSUE TITLE
Update the Domain Manager CLI repo path in User Guide

### ISSUE THREAD

**Issue by nickviola** [cisagov/domain-manager-api#254]
# 💡 Summary #
While looking over the Domain Manager API user guide (https://github.com/cisagov/domain-manager-api/blob/develop/src/user_guide/DomainManager.pdf) I noticed that the CLI repo path in the setup instructions needed to be updated from `cisagov/domain-manager-script`  to `cisagov/domain-manager-cli`

## Motivation and context ##
Keeping the user guide and documentation accurate. Mismatched repo names could cause confusion during setup process.

## Implementation notes ##
Update the path names in blob/develop/src/user_guide/DomainManager.pdf DomainManager.pdf on the following pages:

Page 28: <img width="761" alt="Screen Shot 2021-07-08 at 11 02 54 AM" src="https://user-images.githubusercontent.com/6486652/124956805-fb312300-dfdd-11eb-8eec-71d0bcaa26cd.png">

Page 29: <img width="642" alt="Screen Shot 2021-07-08 at 11 02 41 AM" src="https://user-images.githubusercontent.com/6486652/124956812-fc625000-dfdd-11eb-895c-2542c5bbb80c.png">

## Acceptance criteria ##
- [ ] User guide is updated with the correct CLI repo name.

**Comment by nickviola** [comment]
I have this updated and will submit a PR to address it, but it looks like I do not have access to assign the issue to myself.

**Comment by itsmostafa** [comment]
Hi @nickviola if you'd like i can go in and update this. We are using software called Dr. Explain to modify the user guides.

**Comment by nickviola** [comment]
> Hi @nickviola if you'd like i can go in and update this. We are using software called Dr. Explain to modify the user guides.

@itsmostafa That would be great because It looks like I don't have permission to push my branch up. I mainly just wanted to get this out there to be tracked. If you don't mind updating, that would be perfect. 

In the meantime, I'll see if I can get my permissions updated so I can be helpful in the future. 😀
